# Example: postgres://${USERNAME}:${PASSWORD}@${HOST}:${PORT}/${DATABASE}
source: postgres://source_user:source_pw@localhost:5437/postgres
destination: postgres://dest_user:dest_pw@localhost:5438/postgres

exclude:
  - products

groups:
  country:
    city: "where country_id = 10"
    store: "where city_id IN (SELECT city_id FROM city WHERE country_id = 10)"
    country: "where country_id = 10"

  country_var_1:
    city: "where country_id = {1}"
    store: "where city_id IN (SELECT city_id FROM city WHERE country_id = {1})"
    country: "where country_id = {1}"
    
