
exclude:
  - products

groups:
  country:
    city: "where country_id = 10"
    store: "where city_id IN (SELECT city_id FROM city WHERE country_id = 10)"
    country: "where country_id = 10"

  country_var_1:
    city: "where country_id = {1}"
    store: "where city_id IN (SELECT city_id FROM city WHERE country_id = {1})"
    country: "where country_id = {1}"
    
  country_preserve:
    city: "where country_id = 10"
    store: "where city_id IN (SELECT city_id FROM city WHERE country_id = 10)"
    country: "where country_id = 10"
