version: '3.1'

services:

  source_db:
    image: postgres:15-bullseye
    restart: always
    ports:
      - '5437:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: source_user
      POSTGRES_PASSWORD: source_pw
    networks:
      - pggosync_net
    volumes:
      - source-db-data:/var/lib/postgresql/data
      - ./_seed-data/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - ./_seed-data/dml.sql:/docker-entrypoint-initdb.d/dml.sql

  dest_db:
    image: postgres:15-bullseye
    restart: always
    ports:
      - '5438:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: dest_user
      POSTGRES_PASSWORD: dest_pw
    networks:
      - pggosync_net
    volumes:
      - dest-db-data:/var/lib/postgresql/data
      - ./_seed-data/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql

volumes:
  source-db-data:
  dest-db-data:

networks:
  pggosync_net: