description: This is the default sync configuration for regression testing this project

exclude:
  - products

groups:
  country:
    tables:
      - table: city
        filter: "country_id = 10"
      - table: store
        filter: "city_id IN (SELECT city_id FROM city WHERE country_id = 10)"
      - table: country
        filter: "country_id = 10"

  country_var_1:
    tables:
      - table: city
        filter: "country_id = {1}"
      - table: store
        filter: "city_id IN (SELECT city_id FROM city WHERE country_id = {1})"
      - table: country
        filter: "country_id = {1}"

  country_preserve:
    tables:
      - table: city
        filter: "country_id = 10"
      - table: store
        filter: "city_id IN (SELECT city_id FROM city WHERE country_id = 10)"
      - table: country
        filter: "country_id = 10"
